const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Buttermilk Pancakes: Fluffy and tangy breakfast delights made with buttermilk batter.`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Double Dinner: A meal consisting of two servings or portions, typically enjoyed during an extended dining occasion.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Godzilla Milkshake: A colossal and indulgent dessert featuring towering layers of flavors and toppings.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Country Delight: A rustic and satisfying culinary creation, capturing the essence of comfort and simple pleasures.`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Egg Attack: A culinary creation involving eggs, often cooked or presented in a creative and unexpected manner.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Oreo Dream: A delightful dessert concoction that brings together the classic crunch of Oreo cookies with a creamy and dreamy twist.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Bacon Overflow: A savory abundance of crispy bacon that spills over, satisfying cravings.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `American Classic: A timeless and iconic representation of traditional American culture, style, or cuisine. `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `Quarantine Buddy: A person or companion chosen to share and navigate through isolation and restrictions during challenging times.`,
  },
];
export default menu;
